// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOYPsReoGQuVVoRInBe4jMwCMMXl74Ztc',
    appId: '1:846834471560:android:d264a623d7e007cb55853d',
    messagingSenderId: '846834471560',
    projectId: 'pluschats',
    storageBucket: 'pluschats.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8x6baYfxrapr015ajO_t08ltPF_LunxM',
    appId: '1:846834471560:ios:615a4b5ff84c6aa255853d',
    messagingSenderId: '846834471560',
    projectId: 'pluschats',
    storageBucket: 'pluschats.firebasestorage.app',
    iosBundleId: 'com.plusequalsto.pluschats',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkAqUrxUiVs2F_EVNtBDDiSaZthRIDDco',
    appId: '1:846834471560:web:14c41297a2cdb6d655853d',
    messagingSenderId: '846834471560',
    projectId: 'pluschats',
    authDomain: 'pluschats.firebaseapp.com',
    storageBucket: 'pluschats.firebasestorage.app',
    measurementId: 'G-692TXCK2BR',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8x6baYfxrapr015ajO_t08ltPF_LunxM',
    appId: '1:846834471560:ios:615a4b5ff84c6aa255853d',
    messagingSenderId: '846834471560',
    projectId: 'pluschats',
    storageBucket: 'pluschats.firebasestorage.app',
    iosBundleId: 'com.plusequalsto.pluschats',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkAqUrxUiVs2F_EVNtBDDiSaZthRIDDco',
    appId: '1:846834471560:web:d52e2a394b8f875e55853d',
    messagingSenderId: '846834471560',
    projectId: 'pluschats',
    authDomain: 'pluschats.firebaseapp.com',
    storageBucket: 'pluschats.firebasestorage.app',
    measurementId: 'G-Y1QP2YPZEC',
  );

}